python ./scripts/train.py \
--cfg ./configs/advent.yml \
--cfg_munit ./munit/gta2cityscapes_folder.yaml \
--tensorboard \
--exp-suffix '' \
--data-root path/to/data/ \
--source-domain gta \
--num-classes 19 \
--use-synth-s2t True \
--transl-net munit \
--load-dir-transl /path/to/i2i translation outputs
--batch-size 1 \
--gpu-ids '0' \
--subnorm_type batch \
--data_aug '' \
--var 1 \
--cons_reg '' \
--w_cons_loss 0 \
--end_warm_up_iter 0 \
--use-synth-t2s '' \
--seed 1234 \
--half-adv-cons '' \
--use_ps True \
--round 4 \
--ignore-adv '' \
--start-iter 102000 \
